// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("OpenCLManagedWrapper")]
[assembly: AssemblyProductAttribute("FSCL.Runtime")]
[assembly: AssemblyDescriptionAttribute("FSCL kernel scheduling and execution support")]
[assembly: AssemblyVersionAttribute("2.0.1")]
[assembly: AssemblyFileVersionAttribute("2.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.1";
    }
}
